# Generated by Django 2.1.3 on 2019-05-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oj_name', models.CharField(max_length=20)),
                ('prob_id', models.CharField(max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True, max_length=100)),
                ('link', models.URLField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
