# Generated by Django 2.1.3 on 2019-05-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='No Name', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='varsity_id',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
    ]
