# Generated by Django 2.1.3 on 2019-05-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190530_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='No Status', max_length=100),
        ),
    ]
