# Generated by Django 2.1.3 on 2019-05-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_auto_20190531_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='cut_off',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
