# Generated by Django 2.1.3 on 2019-05-31 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_auto_20190531_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='cut_off',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
