# Generated by Django 2.1.3 on 2019-06-01 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_auto_20190531_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='cut_off_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='cut_off',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
